# Generated by Django 5.2.8 on 2025-11-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=6, unique=True)),
                ('type', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('director', models.CharField(max_length=255)),
                ('cast', models.CharField(max_length=555)),
                ('country', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField()),
                ('release_year', models.IntegerField()),
                ('age_rating', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=12)),
                ('listed_in', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
