# Generated by Django 5.2.8 on 2025-11-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_added',
            field=models.DateField(),
        ),
    ]
