# Generated by Django 5.2.8 on 2025-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movies_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_added',
            field=models.CharField(max_length=255),
        ),
    ]
