# Generated by Django 5.2.8 on 2025-12-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_remove_movies_id_alter_movies_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age_rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date_added',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='listed_in',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
